# Hyper-parameters for training model
# Current states: store the basic hyper-parameters as the defaults

lr: 0.0001
n_box: 4
n_cls: 3
grid_size: 40
attention_layer: 7

anchors: [1., 1., 1.125, 1.125, 1.25, 1.25, 1.375, 1.375]